version: "2"
services:
  nginx:
    build:
        context: .
        dockerfile: Nginx.Dockerfile
    image: ${DOCKER_HUB_ORGANIZATION}/${DOCKER_HUB_PREFIX}nginx
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/runtime/nginx/logs:/etc/logs/nginx
    networks:
       - back
       - reverse-proxy
    volumes_from:
      - fpm
    environment:
      - VIRTUAL_HOST=${BASE_DOMAIN}
    expose:
      - 80
    links:
      - fpm
  fpm:
      image: zvinger/docker-fpm:latest
      working_dir: /var/www
      networks:
        - back
      command: php-fpm
      volumes:
       - ./src:/var/www
       - ./.env:/var/www/.env
      environment:
        XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
        PHP_IDE_CONFIG: serverName=debug

  db:
    image: mysql:5.7
    networks:
      - back
    volumes:
      - ./docker/runtime/mysql:/var/lib/mysql
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: database

networks:
  reverse-proxy:
      external:
        name: reverse-proxy
  back:
    driver: bridge
